---
functional:
  - Регистрация пользователя на сайте должна проходить успешно
  - Авторизация пользователя на сайте должна проходить успешно 
  - Пользователь должен иметь возможность создавать новую игру с ботом
  - Пользователь должен иметь возможность создавать новую игру с другом (создать два аккаунта)
  - Пользователь должен иметь возможность пользоваться чатом
  - Пользователь должен иметь возможность редактировать свой профиль
  - Пользователь должен иметь возможность попробовать игру без регистрации
non-functional:
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  - Пользователь должен иметь возможность просматривать собственную статистику по играм
  - Пользователь должен иметь возможность просматривать профили других игроков-соперников
  - Пользователь должен иметь возможность изменять язык на сайте
  
  
