---
functional:
  - 
  - требование 2
non-functional:
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть безопасным и защищать данные пользователя
implicit:
  - требование 5
  - требование 6
